In [12]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy import types
import pymysql
pymysql.install_as_MySQLdb()
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

from connections import password

In [19]:
# def sql_conn():
# Establish SQL connection
connection_string = (f"root:{password}@localhost/spot_db")
engine = create_engine(f"mysql://{connection_string}")# , pool_recycle=3600, pool_pre_ping=True)

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)
# Save reference to the table
_features = Base.classes.features
_songs = Base.classes.songs
_top = Base.classes.top_200_daily
_viral = Base.classes.viral_50_daily
# Create connection object
session = Session(engine)

In [20]:
features = pd.read_sql(session.query(_features).statement, session.bind)
features.head()

,index,Acousticness,Danceability,Duration_ms,Energy,ID,Instrumentalness,Key,Liveness,Loudness,Mode,Speechiness,Tempo,Time_Signature,Valence
0,805,0.13100,0.748,188491,0.627,000xQL6tZNLJzIrtIgxqSl,0.000000,7,0.0852,-6.029,1,0.0644,120.963,4,0.524
1,4111,0.08220,0.353,193680,0.755,003eoIwxETJujVWmNFMoZy,0.000000,1,0.3900,-6.276,0,0.7330,191.153,4,0.437
2,5461,0.00304,0.619,218747,0.762,007d7JT41sSc1HqWTs4uw7,0.000000,0,0.1220,-6.738,0,0.0692,122.916,4,0.324
3,3606,0.28700,0.620,284856,0.625,00B7TZ0Xawar6NZ00JFomN,0.000000,9,0.3140,-7.438,1,0.5530,167.911,4,0.665
4,5418,0.00587,0.825,220627,0.832,00BuKLSAFkaEkaVAgIMbeA,0.000789,5,0.1140,-5.853,0,0.0403,122.021,4,0.713

In [21]:
songs = pd.read_sql(session.query(_songs).statement, session.bind)
songs.head()

,index,ID,Track,Artist
0,805,000xQL6tZNLJzIrtIgxqSl,Still Got Time,ZAYN
1,4111,003eoIwxETJujVWmNFMoZy,Growing Pains,Alessia Cara
2,5491,007d7JT41sSc1HqWTs4uw7,Love Myself,Hailee Steinfeld
3,3606,00B7TZ0Xawar6NZ00JFomN,Best Life (feat. Chance The Rapper),Cardi B
4,5444,00BuKLSAFkaEkaVAgIMbeA,Telephone,Lady Gaga

In [22]:
top = pd.read_sql(session.query(_top).statement, session.bind)
top.head()

   index Position       date                      ID
0      0        1 2017-01-01  4Km5HrUvYTaSUfiSGPJeQR
1      1        2 2017-01-01  343YBumqHu19cGoGARUTsd
2      2        3 2017-01-01  5aAx2yezTd8zXrkmtKl66Z
3      3        4 2017-01-01  7BKLCZ1jbUBVqRi2FVlTVw
4      4        5 2017-01-01  6fujklziTHa8uoM5OQSfIo

In [23]:
viral = pd.read_sql(session.query(_viral).statement, session.bind)
viral.head()

   index  Position       date                      ID
0      0         1 2017-01-01  1Th5b8AsauED9F7pGv8Yxi
1      1         2 2017-01-01  1D6nV9TPfMnWm7UdVsDVfI
2      2         3 2017-01-01  6F7CjVIrwk7PddQUsoPmoo
3      3         4 2017-01-01  0HEmnAUT8PHznIAAmVXqFJ
4      4         5 2017-01-01  0L0T4tMAaGqLgIVj1MOj9t

In [26]:
features['label'] = features.ID.isin(top.ID)
features.head()

,index,Acousticness,Danceability,Duration_ms,Energy,ID,Instrumentalness,Key,Liveness,Loudness,Mode,Speechiness,Tempo,Time_Signature,Valence,label
0,805,0.13100,0.748,188491,0.627,000xQL6tZNLJzIrtIgxqSl,0.000000,7,0.0852,-6.029,1,0.0644,120.963,4,0.524,True
1,4111,0.08220,0.353,193680,0.755,003eoIwxETJujVWmNFMoZy,0.000000,1,0.3900,-6.276,0,0.7330,191.153,4,0.437,True
2,5461,0.00304,0.619,218747,0.762,007d7JT41sSc1HqWTs4uw7,0.000000,0,0.1220,-6.738,0,0.0692,122.916,4,0.324,True
3,3606,0.28700,0.620,284856,0.625,00B7TZ0Xawar6NZ00JFomN,0.000000,9,0.3140,-7.438,1,0.5530,167.911,4,0.665,True
4,5418,0.00587,0.825,220627,0.832,00BuKLSAFkaEkaVAgIMbeA,0.000789,5,0.1140,-5.853,0,0.0403,122.021,4,0.713,True

In [31]:
features.label.unique()

array([ True, False])